spring:
  application:
    name: booking-service
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: booking-group