# Profile cho development trong IDE
# Sử dụng: chạy Eureka với VM options: -Dspring.profiles.active=ide
server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

