#spring:
#  application:
#    name: station-service
#  datasource:
#    url: jdbc:postgresql://${STATION_INVENTORY_DB_HOST:localhost}:${STATION_INVENTORY_DB_PORT:5434}/${STATION_INVENTORY_DB_NAME:stationdb}
#    username: ${STATION_INVENTORY_DB_USER:ev}
#    password: ${STATION_INVENTORY_DB_PASSWORD:evpass}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#
#  docker:
#    compose:
#      enabled: false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#server:
#  port: 8082
#
#logging:
#  level:
#    org.springframework: INFO
#    com.boilerplate.code: DEBUG
